[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "report-theme-sync"
version = "0.3.0"
dependencies = ["report_theme_assets @ https://github.com/Millstone123/report-theme-assets/archive/refs/tags/v1.2.0.tar.gz"]

[tool.setuptools]
packages = ["theme_sync"]
